version: "3"

services:
  hansel:
    container_name: hansel
    hostname: hansel
    image: debian
    volumes:
      - ./bitcoin-core/bin/bitcoin-cli:/usr/bin/bitcoin-cli
      - ./bitcoin-core/bin/bitcoind:/usr/bin/bitcoind
      - ./hansel:/root/.bitcoin
      - ./wald:/opt/wald
    entrypoint: /opt/wald/entrypoint.sh
    working_dir: /opt/wald
  gretel:
    container_name: gretel
    hostname: gretel
    image: debian
    volumes:
      - ./bitcoin-core/bin/bitcoin-cli:/usr/bin/bitcoin-cli
      - ./bitcoin-core/bin/bitcoind:/usr/bin/bitcoind
      - ./gretel:/root/.bitcoin
      - ./wald:/opt/wald
    entrypoint: /opt/wald/entrypoint.sh
    working_dir: /opt/wald
    links:
      - hansel
  oz:
    container_name: oz
    hostname: oz
    image: node
    volumes:
      - ./oz:/opt/emerald-city
    entrypoint: ["/opt/emerald-city/entrypoint.sh"]
    working_dir: /opt/emerald-city
    links:
      - bitcoinjs-regtest-server
      - gretel
  blockchain-explorer:
    container_name: blockchain-explorer
    hostname: blockchain-explorer
    image: blockstream/esplora
    environment:
      - DISABLE_TOR=1 # blockchain-exporer/runs.sh#L37-L45
      - DISABLE_GENERATETOADDRESS=1 # blockchain-exporer/runs.sh#L256-L263
    ports:
      - 50001:50001
      - 8094:80
    volumes:
      - ./blockchain-explorer:/data
      - ./blockchain-explorer/run.sh:/srv/explorer/run.sh # patch to disable Tor and auto mining of 100 blocks...
    command: ['/srv/explorer/run.sh', 'bitcoin-regtest', 'explorer']
    links:
      - gretel
  bitcoinjs-regtest-server:
    container_name: bitcoinjs-regtest-server
    hostname: bitcoinjs-regtest-server
    image: junderw/bitcoinjs-regtest-server
    ports:
      - 8080:8080
    links:
      - hansel
    volumes:
      - ./bitcoinjs-regtest-server/bitcoin-data:/root/.bitcoin
      - ./bitcoinjs-regtest-server/run_bitcoind_service.sh:/root/run_bitcoind_service.sh # patch to disable mining of 432 blocks...
    