version: "3"

services:
  btc-node1:
    image: debian
    volumes:
      - ../bitcoin-0.20.1/bin/bitcoin-cli:/usr/bin/bitcoin-cli
      - ../bitcoin-0.20.1/bin/bitcoind:/usr/bin/bitcoind
      - ./btc-node-1:/root/.bitcoin
      - ./btc-node-entrypoint.sh:/opt/entrypoint.sh
    entrypoint: /opt/entrypoint.sh
  btc-node2:
    image: debian
    volumes:
      - ../bitcoin-0.20.1/bin/bitcoin-cli:/usr/bin/bitcoin-cli
      - ../bitcoin-0.20.1/bin/bitcoind:/usr/bin/bitcoind
      - ./btc-node-2:/root/.bitcoin
      - ./btc-node-entrypoint.sh:/opt/entrypoint.sh
    entrypoint: /opt/entrypoint.sh
    links:
      - btc-node1
  btc-node3:
    image: node
    volumes:
      - ../bitcoin-0.20.1/bin/bitcoin-cli:/usr/bin/bitcoin-cli
      - ../bitcoin-0.20.1/bin/bitcoind:/usr/bin/bitcoind
      - ./btc-node-3:/root/.bitcoin
      - ./btc-node-entrypoint.sh:/opt/entrypoint.sh
      - ./btc-node3-oracle:/opt/oracle
    entrypoint: /opt/entrypoint.sh
    links:
      - btc-node2