version: "3"

services:
  btc-node1:
    image: debian
    volumes:
      - ../bitcoin-0.20.1/bin/bitcoin-cli:/usr/bin/bitcoin-cli
      - ../bitcoin-0.20.1/bin/bitcoind:/usr/bin/bitcoind
      - ./btc-node-1:/root/.bitcoin
      - ./btc-node-entrypoint.sh:/opt/entrypoint.sh
      - ./shared:/opt/shared
    entrypoint: /opt/entrypoint.sh
  btc-node2:
    image: debian
    volumes:
      - ../bitcoin-0.20.1/bin/bitcoin-cli:/usr/bin/bitcoin-cli
      - ../bitcoin-0.20.1/bin/bitcoind:/usr/bin/bitcoind
      - ./btc-node-2:/root/.bitcoin
      - ./btc-node-entrypoint.sh:/opt/entrypoint.sh
      - ./shared:/opt/shared
    entrypoint: /opt/entrypoint.sh
    links:
      - btc-node1
  btc-node3:
    image: node
    volumes:
      - ../bitcoin-0.20.1/bin/bitcoin-cli:/usr/bin/bitcoin-cli
      - ../bitcoin-0.20.1/bin/bitcoind:/usr/bin/bitcoind
      - ./btc-node-3:/root/.bitcoin
      - ./btc-node-entrypoint.sh:/opt/entrypoint.sh
      - ./shared:/opt/shared
      - ./btc-node3-oracle:/opt/oracle
    entrypoint: /opt/entrypoint.sh
    links:
      - btc-node2
  explorer:
    image: blockstream/esplora
    environment:
      - DISABLE_TOR=1
      - DISABLE_GENERATETOADDRESS=1
    ports:
      - 50001:50001
      - 8094:80
    volumes:
      - ./explorer:/data
      - ./explorer/run.sh:/srv/explorer/run.sh # patch to disable tor and auto mining of 100 blocks...
    command: ['/srv/explorer/run.sh', 'bitcoin-regtest', 'explorer']
    links:
      - btc-node3