version: "3"

services:
  hansel-btc:
    image: debian
    volumes:
      - ./bitcoin-core/bin/bitcoin-cli:/usr/bin/bitcoin-cli
      - ./bitcoin-core/bin/bitcoind:/usr/bin/bitcoind
      - ./hansel-btc:/root/.bitcoin
      - ./btc-node-entrypoint.sh:/opt/entrypoint.sh
      - ./shared:/opt/shared
    entrypoint: /opt/entrypoint.sh
    ports:
      - 18443:18443
  gretel-btc:
    image: debian
    volumes:
      - ./bitcoin-core/bin/bitcoin-cli:/usr/bin/bitcoin-cli
      - ./bitcoin-core/bin/bitcoind:/usr/bin/bitcoind
      - ./gretel-btc:/root/.bitcoin
      - ./btc-node-entrypoint.sh:/opt/entrypoint.sh
      - ./shared:/opt/shared
    entrypoint: /opt/entrypoint.sh
    links:
      - hansel-btc
  oracle-node:
    image: node
    volumes:
      - ./oracle-node:/opt/oracle
    entrypoint: /opt/oracle/entrypoint.sh
    links:
      - bitcoinjs-regtest-server
  explorer:
    image: blockstream/esplora
    environment:
      - DISABLE_TOR=1
      - DISABLE_GENERATETOADDRESS=1
    ports:
      - 50001:50001
      - 8094:80
    volumes:
      - ./explorer:/data
      - ./explorer/run.sh:/srv/explorer/run.sh # patch to disable tor and auto mining of 100 blocks...
    command: ['/srv/explorer/run.sh', 'bitcoin-regtest', 'explorer']
    links:
      - gretel-btc
  bitcoinjs-regtest-server:
    image: junderw/bitcoinjs-regtest-server
    ports:
      - 8080:8080
    links:
      - hansel-btc
    volumes:
      - ./bitcoinjs-regtest-server/bitcoin-data:/root/.bitcoin
      - ./bitcoinjs-regtest-server/run_bitcoind_service.sh:/root/run_bitcoind_service.sh
    